### ISSUE TITLE
Issue with parsing HERE_DOC syntax

### ISSUE THREAD

**Issue by dustinbarnes** [viraptor/phply#31]
I've got a PHP file that has a big heredoc block in it. When I attempt to parse it, I get a recursion limit error: 

``` 
Traceback (most recent call last):
  File "php2json.py", line 31, in <module>
    output, indent=2)
  File "/Library/Python/2.7/site-packages/simplejson/__init__.py", line 276, in dump
    for chunk in iterable:
  File "/Library/Python/2.7/site-packages/simplejson/encoder.py", line 665, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/Library/Python/2.7/site-packages/simplejson/encoder.py", line 515, in _iterencode_list
    for chunk in chunks:
  File "/Library/Python/2.7/site-packages/simplejson/encoder.py", line 515, in _iterencode_list
    for chunk in chunks:
  File "/Library/Python/2.7/site-packages/simplejson/encoder.py", line 634, in _iterencode_dict
    for chunk in chunks:
  File "/Library/Python/2.7/site-packages/simplejson/encoder.py", line 515, in _iterencode_list
    for chunk in chunks:
  File "/Library/Python/2.7/site-packages/simplejson/encoder.py", line 515, in _iterencode_list
    for chunk in chunks:
  File "/Library/Python/2.7/site-packages/simplejson/encoder.py", line 634, in _iterencode_dict
    for chunk in chunks:
  File "/Library/Python/2.7/site-packages/simplejson/encoder.py", line 515, in _iterencode_list
    for chunk in chunks:
  File "/Library/Python/2.7/site-packages/simplejson/encoder.py", line 515, in _iterencode_list
    for chunk in chunks:
  File "/Library/Python/2.7/site-packages/simplejson/encoder.py", line 634, in _iterencode_dict
    for chunk in chunks:
```

And it goes on like that for hundreds or thousands of lines. I'm not sure what structure the data was parsed into, but it appears to be a loop of some sort.

**Comment by viraptor** [comment]
Can you provide the file you used? Or does it happen with any large heredoc?
Also, does the heredoc include any variables, or is it clean text?

**Comment by nijel** [comment]
The problem is probably that heredoc blocks get lexed as way too many tokens, what later leads to quite a lot of BinaryOp calls.

Let's take this example (taken from https://github.com/translate/translate/ testsuite where I'm trying to use phply for parsing PHP files, see https://github.com/translate/translate/pull/3697):

```php
<?php
$lang_register_approve_email = <<<EOT
A new user with the username "{USER_NAME}" has registered in your gallery.

In order to activate the account, you need to click on the link below.

<a href="{ACT_LINK}">{ACT_LINK}</a>
EOT;
```

Is tokenized as:

```
(OPEN_TAG,'<?php\n',1,0)
(VARIABLE,'$lang_register_approve_email',2,6)
(WHITESPACE,' ',2,34)
(EQUALS,'=',2,35)
(WHITESPACE,' ',2,36)
(START_HEREDOC,'<<<EOT\n',2,37)
(ENCAPSED_AND_WHITESPACE,'A',3,44)
(ENCAPSED_AND_WHITESPACE,' new user with the username "{USER_NAME}" has registered in your gallery.\n',3,45)
(ENCAPSED_AND_WHITESPACE,'\n',4,119)
(ENCAPSED_AND_WHITESPACE,'In',5,120)
(ENCAPSED_AND_WHITESPACE,' order to activate the account, you need to click on the link below.\n',5,122)
(ENCAPSED_AND_WHITESPACE,'\n',6,191)
(ENCAPSED_AND_WHITESPACE,'<a href="{ACT_LINK}">{ACT_LINK}</a>\n',7,192)
(END_HEREDOC,'EOT',8,228)
(SEMI,';',8,231)
(WHITESPACE,'\n',8,232)
```

Which ends up in following after parsing:

```
('Assignment',
 {'expr': ('BinaryOp',
           {'left': ('BinaryOp',
                     {'left': ('BinaryOp',
                               {'left': ('BinaryOp',
                                         {'left': ('BinaryOp',
                                                   {'left': ('BinaryOp',
                                                             {'left': 'A',
                                                              'op': '.',
                                                              'right': ' new '
                                                                       'user '
                                                                       'with '
                                                                       'the '
                                                                       'username '
                                                                       '"{USER_NAME}" '
                                                                       'has '
                                                                       'registered '
                                                                       'in '
                                                                       'your '
                                                                       'gallery.\n'}),
                                                    'op': '.',
                                                    'right': '\n'}),
                                          'op': '.',
                                          'right': 'In'}),
                                'op': '.',
                                'right': ' order to activate the account, you '
                                         'need to click on the link below.\n'}),
                      'op': '.',
                      'right': '\n'}),
            'op': '.',
            'right': '<a href="{ACT_LINK}">{ACT_LINK}</a>'}),
  'is_ref': False,
  'node': ('Variable', {'name': '$lang_register_approve_email'})})
```
